services:
  wesleytome:
    image: node:22
    working_dir: /app
    ports:
      - "3000:3000"  # Porta do Next.js
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Adicionar variáveis do Sanity aqui ou usar env_file
    env_file:
      - .env.local  # Carregar variáveis de ambiente
    command: sh -c "corepack enable && pnpm install && pnpm dev"
    tty: true
